= Dynamic routing policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-dynamic-routing/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-dynamic-routing/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]


== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===


== Description
The `dynamic-routing` policy is used to dispatch inbound calls to different targets / endpoints or to rewrite URIs.

This policy is particularly useful for creating API _Mashups_.

Another typical use case is defining this kind of routing:

* Requests from `http://gateway/apis/store/12/info` are redirected to `http://backend_store12/info`
* Requests from `http://gateway/apis/store/45/info` are redirected to `http://backend_store45/info`


== Attributes

|===
|Name |Description

.^|request.endpoint
|The endpoint URL invoked by the gateway after dynamic routing

|===


== Configuration
You can configure multiple rules and their respective redirections relative to the
initial request path.

WARNING: When you define rules, it is important to remember that the API `context-path` must not be part of the rule's path.
For example, if your `context-path` is `/myapi` and your call is `/myapi/123`, if you want to select `123` the regular expression is `/(.*)` (don't forget the `/`).

[[regular-expressions]]
=== Regular expressions

Using regular expressions can be very useful when you want to capture some parts of the initial request path and reuse them to define the redirection.

For example, to capture the end of a path after `/v1/stores/`, the rule path is `/v1/stores/(.*)`. You can then use it in the `redirect to` property: `\http://store_backend/stores/{#group[[0]]}`

You can also use named groups or endpoints, which you define using the APIM *Proxy > Endpoints* function, instead of indexed groups:
`/api/(?<version>v[0-9]+)/stores.*` => `\http://host1/products/api/{#groupName['version']}`

If you redirect to a named group, APIM uses the load balancing algorithm defined for the group to determine how the endpoints are selected. For more information, see link:/apim/3.x/apim_publisherguide_backend_services.html#endpoint-groups[Endpoint groups^].

== Examples

[source, json]
----
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(.*)",
            "url": "http://host2/stores/{#group[0]}"
        }
    ]
}
----

You can also select endpoints configured for your API by name using expression language:

[source, json]
----
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(.*)",
            "url": "{#endpoints['default']}/{#group[0]}"
        }
    ]
}
----

== Errors

=== HTTP status code
|===
|Code |Message

.^| ```400```
| When no rules match the inbound request

|===
